### PR TITLE
Fixing relative path loads in `io`

### PR DESCRIPTION
**Pull request by sneakers-the-rat**
While i was seeing if the 'data' folder was being used in the code, i found that there was a place in `io` where a relative path was used that would fail if the package wasn't being run from the repository root (ie. in cases where one installs from PyPI or etc.). The real way to do this would be to have a `CALIBRATION_DIR` in `prefs` that allows the user to set where their calibration files are, but this PR does some basic path safety stuff:

* if given an absolute path, use it
* if given a relative path that can be resolved to being from the root of the repository/directory containing 'pvp', do that (currently paths are given as `pvp/io/...` so not quite a relative path from the root of the package). 
* if neither of those are true, try to load the relative path
* if that fails, raise an exception with informative error message

before i merge i wanted to make sure with y'all that this doesn't break the actual system

### CODE REVIEW

**Comment by mschottdorf** [comment]
makes sense & looks good to me

**Comment by mschottdorf** [comment]
looks good to me; ready to merge

**Review by mschottdorf — APPROVED** [review]
all good

**Review by CommReteris — APPROVED** [review]

**Review by zajdel — APPROVED** [review]
Fine by me!

**Comment by sneakers-the-rat** [comment]
ok pulled changed from master to this branch and will merge if tests pass

**Pull request merged**
