### PR TITLE
Pcb docs merge with main readthedocs page

### PR DESCRIPTION
**Pull request by zajdel**
Ready to roll pcb-docs into the main branch!

### CODE REVIEW

**Comment by mschottdorf** [comment]
Looks good to me; no changes to the code and all discussed updates to the documentation

**Comment by mschottdorf** [comment]
@zajdel , can you fix the merging conflict? Ist just some async. updates in _docs

**Comment by zajdel** [comment]
> @zajdel , can you fix the merging conflict? Ist just some async. updates in _docs

Done!

**Comment by mschottdorf** [comment]
Awesome! Will merge this

**Pull request merged**
